# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code for Singapore
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineering in the Singapore government:
  overview, who, what and how.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeforsg.github.io" # the base hostname & protocol for your site
github_username:  codeforsg
timezone: Asia/Singapore

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-last-modified-at
